In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [1]:
### sentences
sent = ['the glass of milk', 
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[6480, 6978, 8343, 6623],
 [6480, 6978, 8343, 7531],
 [6480, 5589, 8343, 5453],
 [6963, 9830, 6267, 2535, 5917],
 [6963, 9830, 6267, 2535, 5581],
 [1121, 6480, 4436, 8343, 5593],
 [7636, 6651, 4265, 2535]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6480 6978 8343 6623]
 [   0    0    0    0 6480 6978 8343 7531]
 [   0    0    0    0 6480 5589 8343 5453]
 [   0    0    0 6963 9830 6267 2535 5917]
 [   0    0    0 6963 9830 6267 2535 5581]
 [   0    0    0 1121 6480 4436 8343 5593]
 [   0    0    0    0 7636 6651 4265 2535]]


In [10]:
## feature representation
dim = 10

In [11]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 204ms/step


array([[[ 0.0398905 ,  0.03733229,  0.04153118,  0.00589311,
          0.00985949, -0.02448068, -0.04297514,  0.01474047,
         -0.02779957,  0.00851087],
        [ 0.0398905 ,  0.03733229,  0.04153118,  0.00589311,
          0.00985949, -0.02448068, -0.04297514,  0.01474047,
         -0.02779957,  0.00851087],
        [ 0.0398905 ,  0.03733229,  0.04153118,  0.00589311,
          0.00985949, -0.02448068, -0.04297514,  0.01474047,
         -0.02779957,  0.00851087],
        [ 0.0398905 ,  0.03733229,  0.04153118,  0.00589311,
          0.00985949, -0.02448068, -0.04297514,  0.01474047,
         -0.02779957,  0.00851087],
        [ 0.04915809, -0.01414242, -0.02582206,  0.01742791,
         -0.03272432,  0.03709886,  0.00531974, -0.00563978,
          0.00466108, -0.02261909],
        [-0.01085544,  0.00229717,  0.00471853,  0.03079549,
         -0.00922921, -0.04745566,  0.01967586, -0.01100349,
         -0.00205029,  0.02438262],
        [ 0.04345701, -0.03660321, -0.03523306, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 6480, 6978, 8343, 6623])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 89ms/step


array([[ 0.0398905 ,  0.03733229,  0.04153118,  0.00589311,  0.00985949,
        -0.02448068, -0.04297514,  0.01474047, -0.02779957,  0.00851087],
       [ 0.0398905 ,  0.03733229,  0.04153118,  0.00589311,  0.00985949,
        -0.02448068, -0.04297514,  0.01474047, -0.02779957,  0.00851087],
       [ 0.0398905 ,  0.03733229,  0.04153118,  0.00589311,  0.00985949,
        -0.02448068, -0.04297514,  0.01474047, -0.02779957,  0.00851087],
       [ 0.0398905 ,  0.03733229,  0.04153118,  0.00589311,  0.00985949,
        -0.02448068, -0.04297514,  0.01474047, -0.02779957,  0.00851087],
       [ 0.04915809, -0.01414242, -0.02582206,  0.01742791, -0.03272432,
         0.03709886,  0.00531974, -0.00563978,  0.00466108, -0.02261909],
       [-0.01085544,  0.00229717,  0.00471853,  0.03079549, -0.00922921,
        -0.04745566,  0.01967586, -0.01100349, -0.00205029,  0.02438262],
       [ 0.04345701, -0.03660321, -0.03523306, -0.01327614, -0.00384925,
         0.04203882, -0.00798305, -0.0435837 